$3x-9y = -42$\
$2x + 4y = 2$

In [17]:
import numpy as np

In [18]:
A = np.array([[3,-9],[2,4]])

In [19]:
A

array([[ 3, -9],
       [ 2,  4]])

In [20]:
b = np.array([-42,2])

In [21]:
b

array([-42,   2])

In [22]:
z = np.linalg.solve(A,b)

In [23]:
z

array([-5.,  3.])

$x-2y-z = 6$\
$2x+2y-z = 1$\
$-x-y+2z = 1$

In [33]:
P = np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])

In [34]:
P

array([[ 1, -2, -1],
       [ 2,  2, -1],
       [-1, -1,  2]])

In [35]:
q = np.array([6,1,1])

In [36]:
q

array([6, 1, 1])

In [37]:
s = np.linalg.solve(P,q)

In [38]:
s

array([ 3., -2.,  1.])

 solve following linear equation:\
 $x+y = 4$\
$3x-4y = 2$

In [39]:
A1 = np.array([[1,1],[3,-4]])

In [43]:
A1

array([[ 1,  1],
       [ 3, -4]])

In [44]:
b1 = np.array([4,2])

In [45]:
b1

array([4, 2])

In [47]:
C1 = np.linalg.solve(A1,b1)

In [48]:
C1

array([2.57142857, 1.42857143])