Solve linear euations

$3x-9y = -42$\
$2x+4y = 2$

In [31]:
import numpy as np

In [32]:
A = np.array([[3,-9],[2,4]])

In [33]:
A

array([[ 3, -9],
       [ 2,  4]])

In [34]:
b = np.array([-42,2])

In [35]:
b

array([-42,   2])

In [36]:
z = np.linalg.solve(A,b)

In [37]:
z

array([-5.,  3.])

Problem 2

$x-2y-z = 6$\
$2x+2y-z = 1$\
$-x-y+2z = 1$

In [48]:
A1 = np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])

In [49]:
A1

array([[ 1, -2, -1],
       [ 2,  2, -1],
       [-1, -1,  2]])

In [50]:
b1 = np.array([6,1,1])

In [51]:
b1

array([6, 1, 1])

In [52]:
z1 = np.linalg.solve(A1,b1)

In [53]:
z1

array([ 3., -2.,  1.])